### ISSUE TITLE
Error: "Linker command failed with exit code 1 (use -v to see invocation)"

### ISSUE THREAD

**Issue by rodrigocasillas** [passepartoutvpn/passepartout-ios#34] opened 2019-02-13 20:33 UTC
Hello Davide you've already done enough sharing your project thank you! and I would not like to bother you, but I've already spent 2 days trying to figure out an issue when compiling your project. I'm getting a "Linker command failed with exit code 1 (use -v to see invocation)"

Would you happen to know why Im getting this error? there is not much info about this. Thank you in advance. Cheers!

![logs](https://user-images.githubusercontent.com/39197885/52741868-082bc280-2f9c-11e9-8d11-19c319342389.png)

**Comment by keeshux** [comment] 2019-02-13 20:40
How are you using the library? I suppose not via CocoaPods.

**Comment by rodrigocasillas** [comment] 2019-02-13 22:06
Yes I'm using CocoaPods, I followed your instructions to install the project.  
Installed homebrew to use Git and Ruby packages. Did a pod install in the passepartout-ios directory, created profiles for app and tunnel extension.

**Comment by keeshux** [comment] 2019-02-13 22:09
Then you're opening the `.xcodeproj` whereas you should open the `.xcworkspace`.

**Comment by rodrigocasillas** [comment] 2019-02-13 22:17
Yes thats what I found on stackoverflow but I'm using .xcworkspace. Its a bit frustrating

**Comment by rodrigocasillas** [comment] 2019-02-13 22:22
![screenshot](https://user-images.githubusercontent.com/39197885/52748215-8b084980-2fab-11e9-9267-16af2ee461d1.png)

**Comment by keeshux** [comment] 2019-02-13 22:23
Post a screen of your Xcode environment with the workspace open.

**Comment by rodrigocasillas** [comment] 2019-02-13 22:28
I changed the bundle identifier, could that be an issue?

![screen shot 2](https://user-images.githubusercontent.com/39197885/52748525-534dd180-2fac-11e9-8990-6bf6aed1b0eb.png)

**Comment by keeshux** [comment] 2019-02-13 22:34
Nope, the issue is about linking OpenSSL. Doesn't cleaning change a thing? Try closing Xcode and removing the project directory under `DerivedData`.

**Comment by rodrigocasillas** [comment] 2019-02-13 23:08
Hi keeshux. Yes I've already done that and this error persists. I feel like Im running out of options :(

**Comment by rodrigocasillas** [comment] 2019-02-13 23:10
this should be in red?
![swifty](https://user-images.githubusercontent.com/39197885/52750525-1dabe700-2fb2-11e9-9fb2-5324e064c69c.PNG)

**Comment by rodrigocasillas** [comment] 2019-02-14 03:55
Hello Keeshux, I just saw in your profile that you are from Spain? I'm from Mexico and also like to make some music in my free time. Un Saludo!
I want to ask you about the example app that comes with the tunnel kit library, could it help me create an openVPN conection? or do I have to start from scratch? if so, where can i find documentation on how to implement an openVPN connection with this library? Im an android developer and don't have a lot of experience with iOS but i like to learn new tecnologies. To be honest these mistakes on passepartout have given me a hard time trying to solve them. But i saw your tunnel kit library and got me thinking. Do you think it could help me make a connection?.

And coming back to this issue about linking OpenSSL on passepartout I've again deleted the project directory under Derived Data but it didn't solve the problem.

would appreciate any help thank you!

**Comment by keeshux** [comment] 2019-02-14 07:04
No, I live in Spain, but I'm Italian. Indeed, you should use [TunnelKit](https://github.com/keeshux/tunnelkit) for your project.

**Comment by rodrigocasillas** [comment] 2019-02-15 01:07
Hello! Davide. So I've implemented TunnelKit demo project and guess what, I'm getting the same error. 
Do you think there is something that I'm missing on it's implementation? I mean of course I'm missing something but could you have a guess on what it can be?

![captura de pantalla 2019-02-14 a la s 18 45 47](https://user-images.githubusercontent.com/39197885/52827785-c8dc9f00-308b-11e9-9926-6ff26c4f293e.png)

**Comment by rodrigocasillas** [comment] 2019-02-15 22:35
Hello Davide, I've been configuring the architecture x86_64 since its seem to be part of the problem but had no luck. Do you think the problem is related to the arquitecture configuration?

**Comment by zadr** [comment] 2019-02-16 22:25
I ran into this issue as well, using Xcode 10.1 (10B61) on macOS 10.14.3 (18D109) with cocoapods-1.6.0.

The issue appears to be that the TunnelKit target in Cocoapods is not linking against OpenSSL that is built during `pod install`. 

In the `Pods.xcodeproj` project of the `xcworkspace`, I changed this
<img width="863" alt="screen shot 2019-02-16 at 2 20 47 pm" src="https://user-images.githubusercontent.com/128868/52905904-33115300-31f6-11e9-8718-7ba99b9659f9.png">

to look like this
<img width="862" alt="screen shot 2019-02-16 at 2 24 32 pm" src="https://user-images.githubusercontent.com/128868/52905918-9c916180-31f6-11e9-9b82-277188bdc938.png">

by dragging `Pods/OpenSSL-Apple/frameworks/iPhone/openssl.framework` into Xcode, and then I was able to make it past the linker errors.

Not sure of the appropriate way to fix this in Cocoapods, but, hopefully this points people in the right direction.

**Comment by rodrigocasillas** [comment] 2019-02-18 15:34
Zadr thank you very much! this solved my linker error problem :) Cheers!.

**Comment by keeshux** [comment] 2019-02-18 17:24
I've been away from the project for a while, but let alone my rust I can't figure what's wrong.

What @zadr mentions is not a solution, the pod setup has been fine since forever. Could you guys test with CocoaPods 1.6.0-beta?

**Comment by rodrigocasillas** [comment] 2019-02-18 22:53
keeshux are you using 1.6.0-beta? and what do you mean with "what @zadr mentions is not a solution"? is the app still going to complain?. Also i haven't been able to connect to VPN sever yet, with this project. But have done it with the downloaded app from appstore.

**Comment by keeshux** [comment] 2019-02-18 22:56
That it's not a proper fix, any pod update would scramble it.

**Comment by keeshux** [comment] 2019-02-23 23:37
Looking into this, I can 99.9% _swear_ that this has worked for ages. Xcode may have changed some sh*t as usual.

**Comment by rodrigocasillas** [comment] 2019-02-24 23:43
Hello @keeshux  Ive sent an email to website@davidederosa.com, is it a valid email address?

**Comment by keeshux** [comment] 2019-02-25 09:38
Yes but I need to fix this first.

**Comment by keeshux** [comment] 2019-02-25 10:32
Okay, good news is that I had a stale project copy still working. The flaw happens in the Pods project, so I'm focusing on that.

**Comment by keeshux** [comment] 2019-02-25 10:49
Found the issue, it's caused by a [CocoaPods regression](https://github.com/CocoaPods/CocoaPods/issues/8333).

**Comment by keeshux** [comment] 2019-02-25 11:32
@rodrigocasillas fetch `master` and make sure you always use `bundle exec pod install` rather than `pod install`, in order to use the CocoaPods version imposed by the `Gemfile`.

**Comment by keeshux** [comment] 2019-02-25 21:27
Dude, I'm seriously considering ditching CocoaPods. This is messed up beyond imagination.

**Comment by keeshux** [comment] 2019-02-25 21:42
The right tweak to work around the CocoaPods bug is looking for `TunnelKit.xcconfig` in the Pods project and replacing:

    OTHER_LDFLAGS = $(inherited) -framework "NetworkExtension"

with:

    OTHER_LDFLAGS = $(inherited) -framework "NetworkExtension" -framework "openssl"

Now, I don't have any idea why it is omitted from the linking stage, but it might be some option in the podspec. The unbearable side of things, is that these regressions happen *each* version, so I'm quite fed up with the time I waste more than save with CocoaPods.

**Comment by keeshux** [comment] 2019-02-25 21:58
Not sure, but probably fixed in `9524a72`. Please confirm before I close.

**Comment by rodrigocasillas** [comment] 2019-02-25 22:05
Ok I will check it out a soon as I get home. Changing the subject did you have time to read my email sent to website@davidederosa.com?

**Closed** 2019-02-27 19:17 UTC
Labels: bug
