### ISSUE TITLE
Support for second factor prompts (e.g. TOTP codes)

### ISSUE THREAD

**Issue by jjarava** [passepartoutvpn/passepartout-ios#149] opened 2020-08-08 15:29 UTC
Hi!

All the VPNs I connect to use/require a second authentication factor (a one-time code, usually from a TOTP app like Google Authenticator).

I've imported a perfectly working .ovpn (that I can use in OpenVPN Connect) file into Passepartout, and provided username and password -- but when I try to connect, the only thing I see is "failed authentication" (instead of a prompt for the Authenticator code)

**Comment by keeshux** [comment] 2020-08-08 15:35
Duplicate of #3

**Closed by keeshux** 2020-08-08 15:35 UTC
