### ISSUE TITLE
app run but doesnt connect to my server

### ISSUE THREAD

**Issue by yonamerketing** [passepartoutvpn/passepartout-ios#112] opened 2019-11-07 12:54 UTC
Hi
Here is my problem, thank you for your interest and feel free to ask me more details about
I am able to open the app, 
i added a new host,  by importing my ovpn file, then i put some random credential and i clicked on "use this profile"
but then i click on "enable" and it doesn't work, explicitly:
After I click “enable” it waits 30 seconds, then the “enable” button resets to the off position
here is the output:
[debug ios.txt](https://github.com/passepartoutvpn/passepartout-ios/files/3819564/debug.ios.txt)

Here is my app screenshots:
![IMG_8836](https://user-images.githubusercontent.com/53468775/68389480-bbac9680-016b-11ea-8a3f-34ffe7b45094.PNG)
![IMG_8837](https://user-images.githubusercontent.com/53468775/68389499-c404d180-016b-11ea-97ba-9a4f0609455d.PNG)
![IMG_8838](https://user-images.githubusercontent.com/53468775/68389511-c830ef00-016b-11ea-9c3d-1d01567949a5.PNG)

Besides, when i click on "debug log" it crashes
Here is the output
-
[debug-log-crash.txt](https://github.com/passepartoutvpn/passepartout-ios/files/3819636/debug-log-crash.txt)

**Comment by keeshux** [comment] 2019-11-07 12:59
FYI that crash is because you're using Xcode 11.2, it's a [known issue](#108). About your issue, it's the keychain. Again, you gotta read the README my friend, this section in particular: 

https://github.com/passepartoutvpn/passepartout-ios/#testing

Closing as non-issue.

Good luck!

**Closed by keeshux** 2019-11-07 12:59 UTC

**Comment by yonamerketing** [comment] 2019-11-07 13:11
Hi

i'm sorry
I don't wanna waste your time but i read all the readme, i just don't know
how its work, i'm new on ios, and i don't know how to add groups and
keychain capabilities
Sincerely
Yona

**Comment by keeshux** [comment] 2019-11-07 13:19
You're not wasting my time, the issue is properly described and as long as it's related to the app I'm here to address it. However, you need to also understand that a GitHub repo is not exactly where one learns how to use Xcode. Issues would be a real mess if things got that far, you know. 🙂

**Comment by yonamerketing** [comment] 2019-11-07 15:16
Actually, you're absolutely right :)
i will find it out

**Comment by keeshux** [comment] 2019-11-07 15:20
Thanks for understanding!
