### ISSUE TITLE
Connection gets stuck on Inactive if switching hosts without disconnecting first

### ISSUE THREAD

**Issue by digitalec** [passepartoutvpn/passepartout-ios#129] opened 2020-01-28 16:03 UTC
I’ve been working on troubleshooting a couple of OpenVPN servers and I came across an intermittent issue.

While connected to VPN A, if I switch to VPN B and enable it without first disconnecting from the previous host, the status shows _Disconnecting_ then _Inactive_. At this point I would expect it to automatically connect to VPN B. Sometimes it will but more often than not it will either stay on _Inactive_ until I manually press _Reconnect_ or the app will crash entirely.

This is the debug log after I switched hosts and it got stuck on _Inactive_:

>Failed LINK read: Error Domain=NSPOSIXErrorDomain Code=89 "Operation canceled"
>10:52:02 - Socket state is cancelled (endpoint: xx.xx.xx.xx:1194 -> xx.xx.xx.xx:1194)
>10:52:02 - Cleaning up...
>10:52:02 - Tunnel did stop on request
>10:52:02 - Flushing log...

_Passepartout 1.10.1 (2263)_
_iOS 13.3_

**Comment by keeshux** [comment] 2020-02-27 11:50
@digitalec I remember I had tested and confirmed the issue, but now I can't reproduce it anymore. Can you? How often are you having it?

**Comment by digitalec** [comment] 2020-02-27 13:53
I was able to reproduce it every time until I changed the default gateway to Manual and selected only IPv4.

I’m on T-Mobile which is the reason I have to use that setting or else I can’t communicate to any of my local IPv4 addresses. Of course this redirects all traffic through the VPN but I think this requires me to setup IPv6 on my LAN to fix.

**Comment by keeshux** [comment] 2020-02-27 13:58
Nope, I don't see a relationship there. I think it's rather a matter of how long it takes to disconnect. We'll see.

**Comment by keeshux** [comment] 2020-02-27 15:32
@digitalec please send me an email to beta@passepartoutvpn.app so that I can invite you to TestFlight. There's a chance this might have been fixed as a consequence of fixing #128 and I'd like you to test it, given that I don't experience the issue. Thanks!

**Comment by digitalec** [comment] 2020-02-27 19:07
Email sent

**Comment by keeshux** [comment] 2020-02-28 17:43
However on a second thought I'm pretty sure it won't fix this.

**Comment by keeshux** [comment] 2020-04-06 10:36
Closing this for inactivity (and not reproducible).

**Closed by keeshux** 2020-04-06 10:36 UTC
Labels: bug
