### ISSUE TITLE
“Keep alive on sleep” doesn't seem to work on iOS 13 up to .2

### ISSUE THREAD

**Issue by aleksslarni** [passepartoutvpn/passepartout-ios#106] opened 2019-10-31 22:24 UTC
Hello, 

The most important problem in all of this is disabling the vpn Profile connection when the wifi is disconnected (IOS 13.1, 13.2) and nobody could reach me by call or messages. I understand this problem on side and of iOS but as i know different providers of vpn solve it somehow. Is it possible to add function to prevent sleep wi-fi? (Nevermind if battary will end fast)

**Comment by keeshux** [comment] 2019-11-01 13:41
You should rather elaborate on:

1. What the issue is (= what you expect)
2. The steps to reproduce the issue

because it's not fully clear from your description.

**Comment by aleksslarni** [comment] 2019-11-01 16:14
The problem is that if the phone with enabled VPN is for a long time without activity, the VPN connection is disconnected, so the contacts cannot reach me via Internet messengers by call or message (Signal, threema and etc.)
I need a permanent vpn connection to work even if i do not use the phone for a while (it doesnot matter that the battery will be consumed faster)

I tried to solve the problem in different ways, but apparently this doesnot help

Also i cannot find the function in the iOS settings where you can turn on the background refresh mode of the application

![DB28A974-F84C-4D0E-A9F7-21857C5B4633](https://user-images.githubusercontent.com/57238379/68038803-c682a980-fcdb-11e9-9956-33925a4a32e4.jpeg)

**Comment by aleksslarni** [comment] 2019-11-01 20:15
The problem is that if the phone with enabled VPN is for a long time without activity, the VPN connection is disconnected, so the contacts cannot reach me via Internet messengers by call or message (Signal, threema and etc.)
I need a permanent vpn connection to work even if i do not use the phone for a while (it doesnot matter that the battery will be consumed faster)

I tried to solve the problem in different ways, but apparently this doesnot help

Also i cannot find the function in the iOS settings where you can turn on the background refresh mode of the application

**Comment by keeshux** [comment] 2019-11-01 20:46
What have you tried?

**Comment by aleksslarni** [comment] 2019-11-02 00:41
I use latest iOS and problem happens since 13.1 iOS version. What can try? I tried to use different configs of vpn, i try change wi-fi routers (before worked normally) I cant change your program or iOS. And i ask do you know about this problem? Maybe somebody get same issue? 

I got same problem with original openvpn client for iOS, thats why i bought your program and first time it worked normally and i had stable connection with vpn servers. 

I thinks the problem is in sleep activity and background refresh functions after updates to ios 13 something changes with communication between ios and your programm. Its only my opinion and ill be glad (and many users i think) if you make a focus on this problem because it s very important moment in all of this

**Comment by aleksslarni** [comment] 2019-11-02 01:47
In other words function “Keep alive on sleep” in iOS 13.1/13.2?does not work at all.

**Comment by keeshux** [comment] 2019-11-02 09:21
You're probably the second report ever. I'll keep an eye on it.

**Comment by keeshux** [comment] 2019-11-02 09:23
In the meantime, report a connectivity issue from the app and identify yourself in the description.

**Comment by aleksslarni** [comment] 2019-11-02 16:54
How can i do it from app?

**Comment by keeshux** [comment] 2019-11-03 01:53
Are you using the app from the App Store or you compiled and run it with Xcode?

**Comment by keeshux** [comment] 2019-11-03 16:15
@aleksslarni name the proprietary provider apps that don't exhibit this issue, because they might be using IKEv2.

**Comment by keeshux** [comment] 2019-11-07 21:38
@aleksslarni check this out:

https://www.reddit.com/r/passepartout/comments/dt4rz0/ios_13_is_killing_your_vpn_connection/

**Comment by aleksslarni** [comment] 2019-11-10 23:14
I talked to my friend who develope apps for ios, and he told me that ios 13 coordinately changed system to work with apps. Only super trusted apps like Facebook have normal rights. Dont know what to do. Probably go back on android

**Comment by keeshux** [comment] 2019-11-11 14:52
I asked you several questions and beyond ignoring them you're also not being constructive at all. I'm closing this until another user has something useful to add, you aren't.

**Comment by keeshux** [comment] 2019-12-02 17:46
Moved to more specific issue here: https://github.com/passepartoutvpn/tunnelkit/issues/138

**Comment by keeshux** [comment] 2020-02-21 19:25
Apple never responded, but I haven't experienced this with recent iOS releases. Need to re-test properly.

**Closed** 2020-02-26 22:56 UTC
Labels: bug
