### ISSUE TITLE
Latest update breaks the setting screen

### ISSUE THREAD

**Issue by F3000** [passepartoutvpn/passepartout-ios#161] opened 2021-01-01 18:40 UTC
Hi ,

I can't open my configuration anymore

**Comment by keeshux** [comment] 2021-01-02 08:38
Could you please send a screen recording to issues@passepartoutvpn.app ?

**Comment by keeshux** [comment] 2021-01-02 10:10
Duplicate of #163

**Closed by keeshux** 2021-01-02 10:10 UTC
Labels: bug, ios, regression

**Comment by F3000** [comment] 2021-01-02 11:13
See the other ticket . Re-import has solved the issue
