### ISSUE TITLE
Not works with mobile data

### ISSUE THREAD

**Issue by manveersinghdodiya** [passepartoutvpn/passepartout-ios#125] opened 2019-12-25 06:33 UTC
I have issue with the mobile data when i connect my ovpn file with wifi network it works fine but when i connect with mobile data, vpn not establish connection.

**Comment by keeshux** [comment] 2019-12-25 11:38
Post more info or I will close the issue.

**Comment by manveersinghdodiya** [comment] 2019-12-26 05:17
Some time my ovpn file connect with my server when my device is on mobile network and after 2-3 hours it automatically disconnect and not connect after that even after reinstall tha app but not able to connect again. Then i have to resent iphone network setting then able to connect. But the same file works fine with openvpn official application.

**Comment by keeshux** [comment] 2019-12-26 07:42
Debug logs required.

**Comment by manveersinghdodiya** [comment] 2019-12-26 16:19
[debug-20191226-212136.txt](https://github.com/passepartoutvpn/passepartout-ios/files/4002955/debug-20191226-212136.txt)

**Comment by keeshux** [comment] 2019-12-26 16:31
Okay, duplicate of https://github.com/passepartoutvpn/tunnelkit/issues/145

**Closed by keeshux** 2019-12-26 16:31 UTC

**Comment by manveersinghdodiya** [comment] 2020-02-21 07:57
Some times it connects smoothly but some times not then it hangs device internet.
